option(ENABLE_TESTS "Enable tests" ON)
if(ENABLE_TESTS)
  include(CTest)
  enable_testing()
endif()

function(add_subdirectory_with_tests DIR)
  if(ENABLE_TESTS)
    add_subdirectory(${DIR})
  endif()
endfunction()
